[package]
name = "adventurust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
env_logger = "0.11.5"
fs = "0.0.5"
itertools = "0.13.0"
log = "0.4.22"
regex = "1.11.1"
